<?php

require_once('/nfshome/users/merri/sites/settlers2.net/www/settlers2.php');

page_doctype();
?>Settlers II.net modding<?php
page_title();
?>Modding The Settlers II<?php
page_header();
?>When The Settlers II was originally released the modding culture was still very young, as was the Internet. For this reason people worked on the game by themselves, kept some information secret and released tools as payware. Because there was no mature channel to share stuff the tools didn't bring as much new content as they could have. Today, things are different.<?php
page_description();
?>
				<div class="box">
					<h2>Simplest modifications</h2>
					<p>One of the easiest files to change is the file that holds information of completed campaign missions. This files is located in <kbd>SAVE\MISSION.DAT</kbd>. This file can be opened in a regular text editor. The contents will look something like this: <kbd>1100000000</kbd>. There is a number for each of the ten missions. 0 = mission is not playable, 1 = mission is playable.</p>
					<p>This information can be used for two things: the first is cheating, the second custom campaign packages.</p>
					<h3>Textures and screens</h3>
					<p>The game uses LBM files, which originate from Amiga's Deluxe Paint. The problem with the files of The Settlers II is that they're uncompressed PBM variant, which happens to be a very rare format in the PC world. To give an example, Paint Shop Pro has long been able to both read &amp; write LBM files, but the files it produces by default are compressed and use the ILBM variant of LBM files. You can turn off the compression, but the files are ILBM and make them unusable in The Settlers II.</p>
					<p>Luckily there is a solution to this problem: an old graphics conversion program called Graphic Workshop 1.1Y. This program is able to save the files in Settlers II compatible format, but the settings must be changed before this is possible. Like other programs, it also defaults to compression as well as using the ILBM variant.</p>
					<p style="text-align: center;"><img alt="Graphic Workshop 1.1Y toolbar" src="graphic_workshop_11y_toolbar.png" /></p>
					<p>After installing the program you can see a toolbar in the top of the program window. You can see a green wrench there (eight icon from the right), click it to open options:</p>
					<p style="text-align: center;"><img alt="The Settlers II compatible LBM settings" src="graphic_workshop_11y_lbm.png" /></p>
					<p>As you can see, I have highlighted the correct options: untick "Compress IFF/LBM/PSD files" and tick "LBM files w/ PBM packing". After pressing OK you can now convert any 256 color image you like to The Settlers II compatible format. To do this you can simply move to a folder of you choosing (third icon from right in the toolbar), highlight a file by clicking it and then hitting the first button in the toolbar (Convert between file formats). A window opens and you can select a format you want.</p>
					<p><a href="gwswin11.exe">Download Graphic Workshop 1.1Y</a> (tested to work on Windows 7, Vista and XP)</p>
					<h4>Paint Shop Pro</h4>
					<p>If you are interested on nice old graphics programs, try <a href="http://piittinen.name/files/psp412.exe">Paint Shop Pro 4.12</a> &amp; <a href="http://piittinen.name/files/psp704.exe">Paint Shop Pro 7.04</a> out. I still use the latter one, you can make it work forever simply by opening a file. The 4.12 version works forever with no special tricks even after hitting the 60 day limit. Also, <a href="http://www.irfanview.com/">IrfanView</a> is able to create very good 256 color palettes. May be useful when making custom loading screens!</p>
					<h3>Changing ingame strings</h3>
					<p>There are tools for this purpose: the folks behind The Settlers II.5 have provided TextEditor, which is a simple tool that is able to convert <kbd>DATA\TXT\*.ENG</kbd> and <kbd>DATA\TXT3\ONGAME.ENG</kbd> to XML and thus into easily editable form, open in a regular text editor if you have nothing else. The tool itself requires launching a command prompt, but I've made things easier and have made a ready-to-go package to get you started.</p>
					<p>The self extracting file includes two special batch files: <kbd>xml_to_eng.bat</kbd> and <kbd>eng_to_xml.bat</kbd>. The first one converts XML files to ENG files and the second works the other way around. You only launch the batch file and all the files are converted. I've also readily provided English XML files as well as the resulting ENG files, so you're ready to go modifying the game and mission texts as you please!</p>
					<p><a href="s2text.exe">Download TextEditor &amp; batch files</a></p>
					<h3>Replacing missions</h3>
					<p>In <kbd>DATA\MAPS\</kbd> you can find files such as <kbd>MISS200.WLD</kbd>. These are the mission map files. The good thing about these files is that they are quite much identical with the SWD files generated by the map editor. This means you can make your own missions!</p>
					<p>Of course things aren't this simple: related to this there is a file called <kbd>DATA\MISSIONS\MISS_000.RTX</kbd>. You can open it in a regular text editor. These files contain valuable information on which buildings are available, what resources are in the headquarters, are there any extra animals added, which special graphics (BOBS) are used and events. Events also require a file called <kbd>DATA\TXT\MISS_001.ENG</kbd> that contains the strings that are displayed when a text popup is shown. Complex enough? You bet.</p>
					<p>Your first custom mission doesn't need to be that complex. Simply select a location in map editor that you want to have as finishing point, remove all events (lines starting with <kbd>!MET</kbd>), but remember to preserve the special character at the end of the file (it may appear as a box, a question mark, "sub" or something else). Also add line <kbd>!ENABLE_ALL_HOUSES</kbd> so you can build anything you like. You may also increase the ware lines a bit.</p>
				</div>
<?php
page_footer();
?>