on:
  push:
    branches:    
      - master
name: Build and Publish Settlers II.net
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build --if-present
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp://${{ secrets.FTP_SERVER }}:22/apps/settlers2astro/
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
